version: '3.8'

services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "3000:3000"
    depends_on:
      - stt
      - llm
      - tts
    environment:
      - STT_URL=http://stt:5000
      - LLM_URL=http://llm:5001
      - TTS_URL=http://tts:5002

  stt:
    build: ./stt
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  llm:
    build: ./llm
    ports:
      - "5001:5001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models:/app/models  # Mount local models directory

  tts:
    build: ./tts
    ports:
      - "5002:5002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vad:
    build: ./vad
    ports:
      - "5003:5003"